### ISSUE TITLE
Suggestion: Posibility to disable config entry based on the value of another config entry.

### ISSUE THREAD

**Issue by Bulldog83** [shedaniel/ClothConfig#29] opened 2020-03-01 14:48 UTC
Hello. I want to add a config entry depends of the value of another entry. It would be great if it were possible to disable the config entry based of the value of another entry.

**Comment by shedaniel** [comment] 2020-03-04 13:11
Dupe of #26

**Closed as completed by shedaniel** 2020-03-04 13:11 UTC
Labels: duplicate, enhancement
