### ISSUE TITLE
Please publish Cloth Config to Modrinth

### ISSUE THREAD

**Issue by LoganDark** [shedaniel/ClothConfig#150] opened 2022-03-24 10:03 UTC
CurseForge is incredibly slow and inconvenient to use for me (it also shoves captchas in my face, hCaptcha, the worst one), could you please publish Cloth Config to Modrinth?

**Comment by shedaniel** [comment] 2022-03-24 11:00
Duplicate of https://github.com/shedaniel/RoughlyEnoughItems/issues/694

**Closed as completed by shedaniel** 2022-03-24 11:01 UTC

**Comment by LoganDark** [comment] 2022-03-24 11:03
OK, thanks for the warning

**Comment by hakanai** [comment] 2022-06-03 04:36
LOL, marking a ticket as duplicate where the original isn't even in the same project.

**Comment by LoganDark** [comment] 2022-06-03 15:55
> LOL, marking a ticket as duplicate where the original isn't even in the same project.

This is off-topic.

**Comment by hakanai** [comment] 2022-06-04 06:20
No, it was in reference to https://github.com/shedaniel/cloth-config/issues/150#issuecomment-1077501683 .

Technically, a ticket can only be a duplicate if there was an earlier ticket which is identical. A ticket in another project cannot be identical, as it isn't even a ticket for the same project.

**Comment by LoganDark** [comment] 2022-06-04 11:57
> Technically, a ticket can only be a duplicate if there was an earlier ticket which is identical. A ticket in another project cannot be identical, as it isn't even a ticket for the same project.

This was a request for shedaniel to put one of their libraries on Modrinth. A reference to another issue where they state why they do not put ANY of their libraries/mods on modrinth, is a valid answer.

**Comment by hakanai** [comment] 2022-06-05 05:06
Oh, the answer is absolutely valid, but it would have been more appropriate to have a page somewhere stating why they don't put their mods on Modrinth, and just close all the tickets pointing at that one. Calling it a _duplicate_ is what I was pointing out as wrong.

**Comment by shedaniel** [comment] 2022-06-05 05:51
https://modrinth.com/mod/cloth-config/

**Comment by OrdinaryCloverOC** [comment] 2022-12-12 02:09
https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/3972425 not on modrinth
